### ISSUE TITLE
txtToHTML_V2 Issues - Lab01

### ISSUE THREAD

**Issue by GMOTGIT** [AndreWillomitzer/textToHTML_V2#1] opened 2021-09-16 20:40 UTC

**Comment by GMOTGIT** [comment] 2021-09-16 20:40
Check if argv.i is present. If not, display error message.

**Comment by GMOTGIT** [comment] 2021-09-16 20:41
your tool should generate one .html output file for each input file. For example, if I run the tool on doc.txt a new doc.html file will be generated.

Program accepting only one argument for -i.

**Comment by GMOTGIT** [comment] 2021-09-16 20:41
-o feature just accept folders on the project folder. Folders in other directory are not working

**Comment by GMOTGIT** [comment] 2021-09-16 20:41
If file or directory does not exist on -i , error should be handled properly

**Comment by AndreWillomitzer** [comment] 2021-09-16 20:58
> npm install not working.
Fixed by changing package name to not have capitals, and updating version number.

**Comment by AndreWillomitzer** [comment] 2021-09-16 21:00
> -o feature just accept folders on the project folder. Folders in other directory are not working

This has been addressed by no longer creating the folder if it doesn't exist. The -o feature pushes the HTML file to an EXISTING folder now. It is capable of using an absolute path to find other output destinations.

**Comment by AndreWillomitzer** [comment] 2021-09-16 23:59
-o feature has been fixed to accept existing folders as input, even outside current directory.
-npm install not working has been resolved by reinstalling package.json file and cloning a new repo.
- tool taking only 1 file and 1 folder is intended, not a bug. The examples provided for release 0.1 display this.
- argv.input error checking has been implemented to handle non existent files and folders being passed to the program.

BONUS:
Adjusted the paths to not use split(".") and use path.join() instead. This is safer and more efficient as not all files contain "." such as on Linux where files can have no extensions.

**Closed by AndreWillomitzer** 2021-09-16 23:59 UTC
